# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dae9e33054c597c67ece17c17897cfaef6103bd6429e7cd49b5f24126423fbe2895825e0c72817028e4cb457474fa934a6b00bd749f0991045bd2e3d7c09714

test:
  secret_key_base: cfb31ec192b65e2e4a5b2ee003497ba2c8c6699e91271b5a86bb6ce223168384842e39634cc9d7656d2d06240add0300f0f6b56d0dfc84f10192fdfaa6474bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
